name: CD - Simple Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker images
      run: |
        docker compose build
        
    - name: Deploy notification
      run: |
        echo "✅ Build successful!"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"

